language: objective-c
before_install:
    - brew update
    - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
    - if brew outdated | grep -qx mogenerator; then brew upgrade mogenerator; fi
    - sudo easy_install cpp-coveralls
    - gem install cocoapods
    - gem install rake
script: rake ci
after_success: rake coverage
