def needed_pods
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'
  pod 'FactoryGentleman', :git => 'git://github.com/soundcloud/FactoryGentleman.git', :commit => 'da8fb69'
end

target 'CoreFactoryGentlemanSpec-iOS' do
  platform :ios, :deployment_target => 6.0
  needed_pods
end

target 'CoreFactoryGentlemanSpec-Mac' do
  platform :osx, :deployment_target => 10.8
  needed_pods
end
